name: Deploy to AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sync to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: >
           --follow-symlinks
           --delete
           --exclude '.git/*'
           --exclude '.github/*'
        env:
          AWS_S3_BUCKET: www.jeannimartin.com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'
          SOURCE_DIR: './'